### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by houdelou** [erlyaws/yaws#412]
Hello, I would like to build Yaws on Windows, but it does not seem to work with rebar. First, I got "unrecognized . command". So I tried to replace ./ by .\\ in the script. After I got ".\scripts\rebar-pre-script" is not recognized. After looking into the script, I found this is suppose to be run with /bin/sh. No wonder it is not working... I suppose I have to install cygwin ?

It would be great if it would compile on Windows easily too. I have noticed almost all Erlang web server and framework seem hard to install on Windows OS. I wonder why. Erlang is supposed to be a cross-platform VM no ?

I also saw the downloadable Windows executable but it seems outdated on the site. Is it because it is stable and did not need any rework ?

Thanks !

**Comment by vinoski** [comment]
If you're trying to use `rebar3`, then you should use the `rebar3-support` branch rather than the `master` branch. 

But the bigger problem is that I don't know when Yaws was last built for Windows. We just don't get any requests for Windows support &mdash; well, until now anyway. Whatever Windows executable you found is almost certainly well out of date. And yes, the old Windows support required cygwin.

Getting Yaws to work on Windows 10 would probably not be simple. Installing Windows 10 bash shell support would certainly help. I've used Erlang/OTP for about 14 years, but I don't use Windows at all and so I've never tried to build it or run it there. That said, the [how-to build Erlang on Windows](https://erlang.org/doc/installation_guide/INSTALL-WIN32.html) instructions seem like they're up to date, so maybe building a Windows Erlang/OTP installation isn't too difficult, or perhaps the [Windows installer](http://erlang.org/download/otp_win64_23.2.exe) works just fine. Once that's installed, maybe getting Yaws to work wouldn't be so bad, but I can't say for sure.

**Comment by houdelou** [comment]
Thank you for your answer.

It seems the majority of the Erlang community is on Linux. Maybe I would
have less problems with Windows Subsystem and more support. I'll give it a
try.

I developed an application with gen_server and mnesia database and it works
ok. I like Erlang very much. The problem I have is finding a good web
framework. They look fine but seem unmaintained. So I figured out I could
use Yaws as a web server as it seems to have all the features I need. I
don't really need an ORM and I guess I could implement some features by
myself such as csrf token. The only concern I have is security. It seems
html is not escaped by default on dynamic Yaws web pages. Am I wrong ? I
don't know if it is the right place to discuss such matters. Is there any
forum or mailing list maybe ?

Thanks

Le dim. 31 janv. 2021 à 19:47, Steve Vinoski <notifications@github.com> a
écrit :

**Comment by vinoski** [comment]
There is a mailing list; you can sign up [here](https://sourceforge.net/projects/erlyaws/lists/erlyaws-list). Not much traffic on it. There's also a Slack channel for Yaws under erlanger.slack.com; you can request to join [here](https://erlef.org/slack-invite/erlanger).

Security is always a concern, and Yaws is regularly tested by third parties who file CVEs if warranted. Users sometimes raise security concerns with me directly. In all cases, any issues are addressed as quickly as possible. That said, I'm not aware of any issues with dynamic pages. A dynamic page is typically a mixture of HTML and Erlang code, and the Erlang code generally produces data of various forms, such as more HTML, that are added to the page prior to it being served to the client. If you have specific examples of dynamic pages that reveal security problems, please let me know.

**Comment by houdelou** [comment]
I don't know if this CVE has been addressed :
https://www.cvedetails.com/cve/CVE-2011-5025/. It was registered for the
wiki but I think it could be applicable to Yaws dynamic pages too. For
example, the .net Template system escapes HTML and javascript tags by
default. You have to specify that you want the raw version if you want to
print html tags. If for example a user submit html or js tags in a form and
you display his input on a page, the website is vulnerable to cross-site
scripting attacks. To remedy this vulnerability, you have to escape all
html tags such as < to &lt; But there is no such function in yaws api.
There is one for example in erlydtl template library.

Thanks for your reply and information. By the way, I installed Yaws very
easily on windows subsystem with apt-get on Debian. I think I'll go this
way since I can develop on my Windows box and still run code on Linux.



Le lun. 1 févr. 2021 à 09:00, Steve Vinoski <notifications@github.com> a
écrit :

**Comment by vinoski** [comment]
The wiki is an old bit of code intended just as an example. We should really just remove all the applications other than `yapp`, as I doubt anyone uses them.

**Comment by houdelou** [comment]
Ok, but I think it would still be better to escape tags before displaying
them on dynamic pages. Even those regular pages not related to the wiki.
Normally, this would probably not be the responsibility of a web server,
but since it offers a template mechanism...

Le lun. 1 févr. 2021 à 11:27, Steve Vinoski <notifications@github.com> a
écrit :

**Comment by vinoski** [comment]
Yaws is 20 years old. Not trying to be flippant but I believe if there were really a fundamental quoting/escaping problem, the likelihood that we'd already know about it is extremely high. Off the top of my head I can't think of any Yaws function that takes user input and injects it unchanged into a displayed page; security researchers would have been all over that by now. If you have an example showing the problem and you'd rather not post it because of the security implications, feel free to send it directly to me.

**Comment by vinoski** [comment]
Closing this issue after an offline discussion with @houdelou .
