### ISSUE TITLE
TLS alert no_suitable_signature_algorithm

### ISSUE THREAD

**Issue by ciez** [erlyaws/yaws#414]
a fresh install of yaws 2.0.8 with Erlang OTP 23.2
running `yaws -i` produces these errors:

```
Yaws: Listening to 0.0.0.0:4443 for <1> virtual servers:
 - https://*:4443 under /tmp

TLS server: In state hello at tls_record.erl:539 generated SERVER ALERT: Fatal - Unexpected Message
 - {unsupported_record_type,71} 

SSL accept failed: {tls_alert,
                       {unexpected_message,
                           "TLS server: In state hello at tls_record.erl:539 generated SERVER ALERT: Fatal - Unexpected Message\n {unsupported_record_type,71}"}}

TLS server: In state hello at ssl_handshake.erl:1549 generated SERVER ALERT: Fatal - Insufficient Security
 - no_suitable_signature_algorithm

SSL accept failed: {tls_alert,
                       {insufficient_security,
                           "TLS server: In state hello at ssl_handshake.erl:1549 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_signature_algorithm"}}

TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown

SSL accept failed: {tls_alert,
                       {certificate_unknown,
                           "TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown\n"}}
```

edit:

apologies for confusion:
the error shows up when accessing https://0.0.0.0:4443/ (not when running yaws -i)
here is an additional error message:
```
SSL accept failed: {tls_alert,
                       {insufficient_security,
                           "TLS server: In state hello at ssl_handshake.erl:1549 generated SERVER ALERT: Fatal - Insufficient Security\n no_suitable_signature_algorithm"}}

TLS server: In state abbreviated received CLIENT ALERT: Fatal - Certificate Unknown

SSL accept failed: {tls_alert,
                       {certificate_unknown,
                           "TLS server: In state abbreviated received CLIENT ALERT: Fatal - Certificate Unknown\n"}}
```

**Comment by vinoski** [comment]
Just last week I built Erlang/OTP 23.2 and Yaws 2.0.8 from their tarballs, installed on Linux, and I didn't see any errors like this. I just stopped it and ran `yaws -i` to be sure, and there were no problems. I also tried on macOS Catalina and saw no problems there either. Clearly, something is different between your configuration and mine, and it's difficult to try to fix things that I can't reproduce.

Is this installation using the default `yaws.conf` file, or a customized conf?

If you run `yaws -i`, then run these commands at the Erlang shell prompt:

    1> rr(yaws_server).
    2> rp(yaws_api:getconf()).

The second command will dump the whole server config to the screen. Find the `sconf` for the server on port 4443, and check its `ssl` field. Does it have `protocol_version` set to something other than `undefined`?

**Comment by ciez** [comment]
output of the yaws -i, rr, rp:
[yaws-debug.txt](https://github.com/erlyaws/yaws/files/6097152/yaws-debug.txt)

yaws.conf renamed to *.txt to enable upload to github:
[yaws.conf.txt](https://github.com/erlyaws/yaws/files/6097154/yaws.conf.txt)

the OS is RHEL 7.9
openssl, openssl-devel were installed when building both OTP and Yaws

**Comment by vinoski** [comment]
OK, thanks, the configuration looks standard. Thanks also for the clarification in the first posting; I was pretty sure it was a case of "insufficient security" due to the value of 71 present in the errors, as 71 is the standard TLS alert value for that case.

What client are you using to cause the errors?

**Comment by ciez** [comment]
using Chrome Version 89.0.4389.82 (Official Build) (64-bit)
on the same server

**Comment by ciez** [comment]
I will try to upgrade openssl to 1.1.1, rebuild OTP & Yaws, and see if this setup works any different

**Comment by vinoski** [comment]
Well, that's not really going to help. Generally, web servers don't ship with out-of-the-box fully operational certificates and such in place, because we're not in the business of satisfying full security needs for all domains. If you want https to work correctly, you'll have to supply your own certificates particular to your domain and configure Yaws to use them.

That said, if in Chrome you get the error page about the connection not being private, you should be able to click on the Advanced button and choose to proceed anyway and thereby get Yaws to serve a page. By the default config, that page would be a directory listing for `/tmp`. But this currently doesn't work, because the default config has a wildcard server name `<server *>` along with a non-default port `port = 8443`, and the wildcard matching code fails when you try to visit something like `https://127.0.0.1:8443/` because it's not properly accounting for the port specification in the hostname. I have a fix for this, but I'd like to add a test for it before committing it.

**Comment by ciez** [comment]
well I upgraded openssl after reading a suggestion on their website to upgrade. It wasn't difficult.

rebuilt OTP, Yaws. Generated a new self-signed PEM as per [this hint](https://www.ibm.com/support/knowledgecenter/SSMNED_5.0.0/com.ibm.apic.cmc.doc/task_apionprem_gernerate_self_signed_openSSL.html)

now only 1 error shows:
```
Yaws: Listening to 127.0.0.1:4443 for <1> virtual servers:
 - https://*:4443 under /var/yaws/www

=NOTICE REPORT==== 7-Mar-2021::19:08:19.710746 ===
TLS server: In state wait_finished received CLIENT ALERT: Fatal - Certificate Unknown

=ERROR REPORT==== 7-Mar-2021::19:08:19.711028 ===
SSL accept failed: {tls_alert,
                       {certificate_unknown,
                           "TLS server: In state wait_finished received CLIENT ALERT: Fatal - Certificate Unknown\n"}}

```

**insufficient_security** seems to be fixed.

I understand that for production deployment a proper cert is necessary and the url address should match that on the cert.

Will ignore the **certificate_unknown** error for the moment.

Thank you kindly Steve for your prompt response! 
Much appreciated.
